Repository graphprotocol/graph-tooling, pull requests merged in 2018-11, with the labels that each got.

#161 compiler: Add contents `graph-ts/global` to libs
  src/compiler.js
Labels: pending review

#165 package.json: Remove old `graph-build` and `graph-codegen` executables
  package.json
Labels: area/cli, bug, pending review

#162 Update README: Include deploy and remove in list of commands, readability and consistency updates
  README.md
Labels: pending review

#171 Travis: Run `graph auth` as part of the test commands
  .travis.yml
Labels: enhancement, pending review
