Repository graphprotocol/graph-tooling, pull requests merged in 2018-09, with the labels that each got.

#101 graph-deploy: Take `--api-key` option for auth
  graph-deploy.js
Labels: pending review

#104 runtime: Add `fromArray` and `setArray`
  examples/example-event-handler/dist/ExampleSubgraph/ExampleSubgraph.ts
  index.d.ts
  src/runtime/index.ts
Labels: pending review

#110 Fix loading ABIs built by Truffle
  src/cli/abi.js
  src/cli/compiler.js
Labels: bug, pending review

#113 runtime: Replace `Array<T>` with `Array<Value>`
  examples/example-event-handler/dist/ExampleSubgraph/ExampleSubgraph.ts
  index.d.ts
  src/runtime/index.ts
Labels: pending review

#114 runtime: Make `store.get` always fail
  examples/example-event-handler/dist/ExampleSubgraph/ExampleSubgraph.ts
  examples/example-event-handler/dist/ExampleSubgraph/ExampleSubgraph.wasm
  examples/example-event-handler/dist/ExampleSubgraph/abis/ExampleContract.json
  examples/example-event-handler/dist/schema.graphql
  examples/example-event-handler/mapping.ts
  examples/example-event-handler/schema.graphql
  src/runtime/index.ts
Labels: pending review

#109 Use namespaced package name
  package.json
Labels: pending review

#122 index.d.ts: Add `ipfs` and `json` namespaces
  index.d.ts
Labels: pending review

#123 runtime, cli: Remove `block_hash` parameter from `bind`
  examples/example-event-handler/dist/ExampleSubgraph/ExampleSubgraph.ts
  src/cli/abi.js
  src/runtime/index.ts
Labels: pending review

#127 runtime: Remove dead `blockHash` parameter
  examples/example-event-handler/dist/ExampleSubgraph/ExampleSubgraph.ts
  examples/example-event-handler/types/ExampleSubgraph/ExampleContract.types.ts
  src/runtime/index.ts
Labels: bug, pending review

#130 README: Add NPM version badge
  README.md
Labels: documentation, enhancement, pending review

#118 docs: Add info about `graph deploy`
  README.md
Labels: pending review

#132 runtime: Add `crypto.keccak256` host import
  index.d.ts
  src/runtime/index.ts
Labels: pending review

#133 Enable store.get again and allow it to return `null`
  index.d.ts
  src/runtime/index.ts
Labels: enhancement, pending review

#135 GetArray: declaration and signature fix
  index.d.ts
  src/runtime/index.ts
Labels: pending review
