Repository graphprotocol/graph-tooling, pull requests merged in 2018-10, with the labels that each got.

#144 Normalize Truffle and non-Truffle ABIs in build output
  src/compiler.js
Labels: admin, area/cli, pending review

#138 slight doc change to graph-cli
  README.md
Labels: pending review

#139 Update graph-cli dependency in example subgraph
  examples/example-event-handler/package.json
  examples/example-event-handler/yarn.lock
Labels: chore, pending review

#151 small typo fix
  README.md
Labels: pending review

#152 README: Remove now optional subgraph.yaml from example commands
  README.md
Labels: documentation, enhancement, pending review

#153 graph.js: Fix `graph deploy`
  graph.js
Labels: pending review

#155 Print routes returned by graph node
  graph.js
Labels: pending review

#156 Support abi under compilerOutput
  src/abi.js
Labels: pending review
