Repository graphprotocol/graph-tooling, pull requests merged in 2019-02, with the labels that each got.

#208 Make it harder to use unprefixed subgraph names, add advice to graph deploy errors
  graph.js
Labels: developer experience, enhancement, ethdenver, pending review

#219 Interface fields are valid
  src/validation/schema.js
Labels: pending review

#221 Reject entity fields with arguments as part of validation
  src/validation/schema.js
  tests/cli/validation.test.js
  tests/cli/validation/entity-field-args.stderr
  tests/cli/validation/entity-field-args/Abi.json
  tests/cli/validation/entity-field-args/mapping.ts
  tests/cli/validation/entity-field-args/schema.graphql
  tests/cli/validation/entity-field-args/subgraph.yaml
Labels: area/cli, bug, pending review
