Repository graphprotocol/graph-tooling, pull requests merged in 2019-05, with the labels that each got.

#263 graph init: Skip Etherscan if --abi is provided
  src/commands/init.js
Labels: area/cli, bug, developer experience, pending review

#262 Fix uncaught exceptions caused by incorrect async mapping
  src/type-generator.js
Labels: area/cli, bug, developer experience, pending review

#264 Assert expected stdout/stderr before exit code in CLI tests
  tests/cli/util.js
Labels: area/cli, chore, enhancement, pending review

#265 Fail subgraph validation if functions are not found in ABIs
  src/subgraph.js
  tests/cli/validation.test.js
  tests/cli/validation/call-function-not-found.stderr
Labels: area/cli, bug, developer experience, pending review

#268 Add note at the top of all generated files (#212)
  src/type-generator.js
Labels: chore, developer experience, pending review

#267 graph init: Improve error when ABIs are not found on Etherscan
  src/commands/init.js
Labels: area/cli, bug, developer experience, pending review

#274 package.json: bump keytar version
  package.json
  yarn.lock
Labels: pending review

#273 Add `log` calls to the example subgraph
  examples/example-subgraph/src/mapping.ts
  examples/example-subgraph/yarn.lock
Labels: area/cli, enhancement, pending review

#276 Allow stateMutability 'nonpayable' in generated functions.
  src/codegen/abi.js
Labels: area/cli
