Repository graphprotocol/graph-tooling, pull requests merged in 2019-01, with the labels that each got.

#188 Sam/january doc edits
  README.md
Labels: pending review

#178 Small update to documentation
  README.md
Labels: documentation, pending review

#194 Fix logger ReferenceError
  graph.js
Labels: pending review

#196 Jannis/fix tests
  .travis.yml
Labels: pending review

#201 Add API version to URL path automatically
  graph.js
Labels: pending review

#202 Allow graph-node to provide full URLs
  graph.js
Labels: enhancement, pending review
