Repository graphprotocol/graph-tooling, pull requests merged in 2019-04, with the labels that each got.

#239 Fix withSpinner and example subgraph value bugs
  src/command-helpers/spinner.js
  src/subgraph.js
  tests/cli/validation/example-values-found/subgraph.yaml
Labels: bug, pending review

#240 Make contract addresses in the manifest optional
  manifest-schema.graphql
  src/subgraph.js
  tests/cli/validation.test.js
  tests/cli/validation/source-without-address-is-valid.stderr
  tests/cli/validation/source-without-address-is-valid/Abi.json
  tests/cli/validation/source-without-address-is-valid/mapping.ts
  tests/cli/validation/source-without-address-is-valid/schema.graphql
  tests/cli/validation/source-without-address-is-valid/subgraph.yaml
Labels: new feature, pending review

#242 Fix graph-ts version for the apiVersion bump to > 0.5.1 as intended
  src/migrations/bump-mapping-api-version.js
Labels: bug, pending review

#247 De-duplicate event names and contract function names
  src/codegen/abi.js
Labels: pending review

#249 compiler, type-generator: Fix loading subgraphs in --watch mode
  src/compiler.js
  src/type-generator.js
Labels: bug, pending review

#250 Change naming of event params classes
  src/codegen/abi.js
Labels: pending review

#246 Add `topic0` field to event handlers
  .gitignore
  manifest-schema.graphql
  tests/cli/validation.test.js
  tests/cli/validation/topic0-is-valid/Abi.json
  tests/cli/validation/topic0-is-valid/mapping.ts
  tests/cli/validation/topic0-is-valid/schema.graphql
  tests/cli/validation/topic0-is-valid/subgraph.yaml
Labels: pending review
